name: Read Vault Secrets with OIDC
on:
    workflow_dispatch:
jobs:
    read_vault_secret:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Debug OIDC Token
              run: |
                 curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                 "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/mniranjanrorg" | jq

            - name: Read Vault Secrets
              uses: hashicorp/vault-action@v3.0.0
              with:
                url: "http://ec2-52-87-173-144.compute-1.amazonaws.com:8200/"
                method: jwt
                role: "aabk_jwt_role"
                secrets: |
                  /v1/kv/data/aabk/dev/pipeline/sp username | USER_NAME;
                  /v1/kv/data/aabk/dev/pipeline/sp password | PASS_WORD

            - name: Debug secrets (masked)
              run: |
                echo "Username: ${{ secrets.USER_NAME }}"  # Will be masked in logs
                echo "Password: ${{ secrets.PASS_WORD }}"  # Will be masked in logs
    
                # Alternative for testing (values will be visible in logs)
                echo "::add-mask::${{ env.USER_NAME }}"
                echo "::add-mask::${{ env.PASS_WORD }}"
                echo "Unmasked Username: ${{ env.USER_NAME }}"
                echo "Unmasked Password: ${{ env.PASS_WORD }}"